# Generated by Django 4.2.9 on 2024-01-05 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_alter_posts_options_alter_posts_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responses',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AddField(
            model_name='responses',
            name='text',
            field=models.TextField(default='', verbose_name='Текст отклика'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отклика'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.posts', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.CharField(choices=[('U', 'Undefined'), ('A', 'Accepted'), ('D', 'Deleted')], default='U', max_length=1, verbose_name='Состояние отклика'),
        ),
    ]
